package ch.cern.eam.wshub.core.services.workorders.entities;

import ch.cern.eam.wshub.core.annotations.InforField;
import net.datastream.schemas.mp_fields.NOUN_Type;
import net.datastream.schemas.mp_fields.VERB_Type;

import java.io.Serializable;
import java.math.BigInteger;

public class WorkOrderActivityCheckListDefault implements Serializable {
    @InforField(xpath = "WORKORDERID/JOBNUM")
    private String workOrderId;

    @InforField(xpath = "WORKORDERID/auto_generated")
    private Boolean autoGeneratedWorkOrderId = true;

    @InforField(xpath = "ACTIVITYCODE/value")
    private BigInteger activityCode;

    @InforField(xpath = "ACTIVITYCODE/auto_generated")
    private String autoGeneratedActivityCode = "false";

    @InforField(xpath = "JOBSEQUENCE")
    private BigInteger jobSequence;

    @InforField(xpath = "verb")
    private VERB_Type verb;

    @InforField(xpath = "noun")
    private NOUN_Type noun;

    @InforField(xpath = "version")
    private String version;

    public  WorkOrderActivityCheckListDefault(){
        version = "001";
        verb = VERB_Type.GET;
        noun = NOUN_Type.WORK_ORDER_ACTIVITY_CHECK_LIST_DEFAULT;
    }

    public String getWorkOrderId() {
        return workOrderId;
    }

    public void setWorkOrderId(String workOrderId) {
        this.workOrderId = workOrderId;
    }

    public Boolean getAutoGeneratedWorkOrderId() {
        return autoGeneratedWorkOrderId;
    }

    public void setAutoGeneratedWorkOrderId(Boolean autoGeneratedWorkOrderId) {
        this.autoGeneratedWorkOrderId = autoGeneratedWorkOrderId;
    }

    public BigInteger getActivityCode() {
        return activityCode;
    }

    public void setActivityCode(BigInteger activityCode) {
        this.activityCode = activityCode;
    }

    public String getAutoGeneratedActivityCode() {
        return autoGeneratedActivityCode;
    }

    public void setAutoGeneratedActivityCode(Boolean autoGeneratedActivityCode) {
        this.autoGeneratedActivityCode = Boolean.toString(autoGeneratedActivityCode);
    }

    public void setAutoGeneratedActivityCode(String autoGeneratedActivityCode) {
        this.autoGeneratedActivityCode = autoGeneratedActivityCode;
    }

    public BigInteger getJobSequence() {
        return jobSequence;
    }

    public void setJobSequence(BigInteger jobSequence) {
        this.jobSequence = jobSequence;
    }

    public VERB_Type getVerb() {
        return verb;
    }

    public void setVerb(VERB_Type verb) {
        this.verb = verb;
    }

    public NOUN_Type getNoun() {
        return noun;
    }

    public void setNoun(NOUN_Type noun) {
        this.noun = noun;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }
}
